// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OsiguranjeVozila.Data;

#nullable disable

namespace OsiguranjeVozila.Migrations
{
    [DbContext(typeof(OsiguranjeDbContext))]
    [Migration("20250608145212_Remove Klijent-Vozilo table")]
    partial class RemoveKlijentVozilotable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Klijent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klijenti");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Polise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NominalniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SlikaPolise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Polise");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.ProdajaPolise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KlijentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolisaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UcesceUSteti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VoziloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KlijentId");

                    b.HasIndex("PolisaId");

                    b.HasIndex("VoziloId");

                    b.ToTable("Prodaje");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.UslovOsiguranja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UslovOsiguranja");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Vozilo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojSasije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPrveRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<float>("Kubikaza")
                        .HasColumnType("real");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistarskaOznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SnagaMotora")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("PoliseUslovOsiguranja", b =>
                {
                    b.Property<Guid>("PoliseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsloviOsiguranjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PoliseId", "UsloviOsiguranjaId");

                    b.HasIndex("UsloviOsiguranjaId");

                    b.ToTable("PoliseUslovOsiguranja");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.ProdajaPolise", b =>
                {
                    b.HasOne("OsiguranjeVozila.Models.Domain.Klijent", "Klijent")
                        .WithMany("Prodaje")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsiguranjeVozila.Models.Domain.Polise", "Polisa")
                        .WithMany("Prodaje")
                        .HasForeignKey("PolisaId");

                    b.HasOne("OsiguranjeVozila.Models.Domain.Vozilo", "Vozilo")
                        .WithMany("Prodaje")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Polisa");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("PoliseUslovOsiguranja", b =>
                {
                    b.HasOne("OsiguranjeVozila.Models.Domain.Polise", null)
                        .WithMany()
                        .HasForeignKey("PoliseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsiguranjeVozila.Models.Domain.UslovOsiguranja", null)
                        .WithMany()
                        .HasForeignKey("UsloviOsiguranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Klijent", b =>
                {
                    b.Navigation("Prodaje");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Polise", b =>
                {
                    b.Navigation("Prodaje");
                });

            modelBuilder.Entity("OsiguranjeVozila.Models.Domain.Vozilo", b =>
                {
                    b.Navigation("Prodaje");
                });
#pragma warning restore 612, 618
        }
    }
}
